import Link from "next/link";

export default function PrivacyPage() {
  return (
    <main className="max-w-legal mx-auto px-6 py-24">
      <Link href="/" className="text-body-sm text-muted mb-10 inline-block">
        ← Back to home
      </Link>
      <h1 className="text-h2-sm font-medium mb-8">Privacy Policy</h1>
      <div className="flex flex-col gap-6 text-body-sm text-muted">
        <p>
          This page is a placeholder. Otlo&rsquo;s real Privacy Policy belongs here once
          it&rsquo;s been drafted and reviewed by counsel — not generated by a copywriting
          pass. Do not treat the text below as binding.
        </p>
        <h2 className="text-charcoal font-medium mt-4">The principle this will encode</h2>
        <p>
          Member data belongs to the community that gathered it, not to Otlo — said here,
          not just in the product. What we collect, how builders and members can export or
          delete it, what member-recognition features do and don&rsquo;t track (recognition,
          never surveillance), and what, if anything, is shared with brand partners and
          under what consent.
        </p>
        <h2 className="text-charcoal font-medium mt-4">Before this goes live</h2>
        <p>Have this section replaced with counsel-reviewed terms before public launch.</p>
      </div>
    </main>
  );
}
