import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="max-w-legal mx-auto px-6 py-24">
      <Link href="/" className="text-body-sm text-muted mb-10 inline-block">
        ← Back to home
      </Link>
      <h1 className="text-h2-sm font-medium mb-8">Terms of Service</h1>
      <div className="flex flex-col gap-6 text-body-sm text-muted">
        <p>
          This page is a placeholder. Otlo&rsquo;s real Terms of Service belong here once
          they&rsquo;ve been drafted and reviewed by counsel — not generated by a copywriting
          pass. Do not treat the text below as binding.
        </p>
        <h2 className="text-charcoal font-medium mt-4">What this will cover</h2>
        <p>
          Account eligibility and registration, acceptable use of the platform, the
          community builder&rsquo;s ownership of their member data and export rights, payment
          and subscription terms, marketplace and vendor booking terms, Event IP
          provenance and licensing (described precisely — never as a legal right Otlo
          grants), and termination.
        </p>
        <h2 className="text-charcoal font-medium mt-4">Before this goes live</h2>
        <p>Have this section replaced with counsel-reviewed terms before public launch.</p>
      </div>
    </main>
  );
}
